[build]
functions = "./functions"

[functions]
node_bundler = "esbuild"
external_node_modules = ["busboy", "node-fetch"]

[[redirects]]
from = "/image/uploadfile"
to = "/.netlify/functions/image"
status = 200
force = true

[[redirects]]
from = "/image/uploadfiles"
to = "/.netlify/functions/image"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/.netlify/functions/index"
status = 200
force = true